image: paiboon15721/node-docker-compose
pipelines:
  branches:
    custom-deploy:
      - step:
          script:
            - scp ./docker-stack.yml $DEPLOY_USER_AND_HOST:/home/paiboon/
            - ssh $DEPLOY_USER_AND_HOST 'bash -s' < ./deploy.sh

options:
  docker: true