version: '3.2'
services:
  hackathon2017-frontend:
    image: paiboon15721/hackathon2017-frontend
    networks:
      - app-network
    depends_on:
      - hackathon2017-auth-api
      - hackathon2017-rooms-api
      - hackathon2017-bookings-api
      - hackathon2017-reports-api
      - hackathon2017-owners-api
    ports:
      - '80:80'
  hackathon2017-auth-api:
    image: paiboon15721/hackathon2017-auth-api
    networks:
      - app-network
      - db-network
    depends_on:
      - mongo-db
    environment:
      - MONGO_DB_HOST=mongo-db
    deploy:
      replicas: 2
  hackathon2017-rooms-api:
    image: paiboon15721/hackathon2017-rooms-api
    networks:
      - app-network
      - db-network
    depends_on:
      - mongo-db
    environment:
      - MONGO_DB_HOST=mongo-db
    deploy:
      replicas: 2
  hackathon2017-bookings-api:
    image: paiboon15721/hackathon2017-bookings-api
    networks:
      - app-network
      - db-network
    depends_on:
      - mongo-db
    environment:
      - MONGO_DB_HOST=mongo-db
    deploy:
      replicas: 2
  hackathon2017-reports-api:
    image: paiboon15721/hackathon2017-reports-api
    networks:
      - app-network
      - db-network
    depends_on:
      - mongo-db
    environment:
      - MONGO_DB_HOST=mongo-db
    deploy:
      replicas: 2
  hackathon2017-owners-api:
    image: paiboon15721/hackathon2017-owners-api
    networks:
      - app-network
      - db-network
    depends_on:
      - mongo-db
    environment:
      - MONGO_DB_HOST=mongo-db
    deploy:
      replicas: 2
  mongo-db:
    image: mongo
    networks:
      - db-network
    volumes:
      - mongo-data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.type == mongodb
networks:
  app-network:
    driver: overlay
  db-network:
    driver: overlay
volumes:
  mongo-data:
      