exports.getRoomsList = require('./getRoomsList')
exports.getRoom = require('./getRoom')
exports.addBooking = require('./addBooking')
exports.getBookingsList = require('./getBookingsList')
exports.updateBooking = require('./updateBooking')
exports.getOwnersList = require('./getOwnersList')
exports.getBooking = require('./getBooking')
exports.seedData = require('./seedData')
