exports.getRoomsList = require('./getRoomsList')
exports.getRoom = require('./getRoom')
exports.addBooking = require('./addBooking')
exports.getBookingsList = require('./getBookingsList')
exports.updateBooking = require('./updateBooking')
