exports.getRoomsList = require('./getRoomsList')
exports.getRoom = require('./getRoom')
exports.getOwnersList = require('./getOwnersList')
exports.addBooking = require('./addBooking')
exports.getNoSlipBookingsList = require('./getNoSlipBookingsList')
exports.updateBooking = require('./updateBooking')
exports.getBookingsList = require('./getBookingsList')
